version: '3.8'

networks:
  project_network:
    name: ${APP_NAME}_network
    driver: bridge

services:

  php-fpm:
    image: ${REPO_NAME}_app:${VERSION}
    container_name: ${APP_NAME}_app
    user: ${CURRENT_UID}
    build:
      context: ./containers/php-fpm
      args:
        gd: ${GD}
        imagick: ${IMAGICK}
        xdebug: ${XDEBUG}
    volumes:
      - ${APP_SRC}:/var/www/html
    expose:
      - 9000
      - 9003
    depends_on:
      - mysql
    networks:
      - project_network

  mysql:
    image: ${REPO_NAME}_mysql:${VERSION}
    container_name: ${APP_NAME}_mysql
    user: ${CURRENT_UID}
    restart: on-failure
    build:
      context: ./containers/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./containers/mysql/dbdata:/var/lib/mysql
    expose:
      - ${MYSQL_PORT}
    ports:
      - 3306:3306
    networks:
      - project_network
  
  nginx:
    restart: on-failure
    image: ${REPO_NAME}_nginx:${VERSION}
    container_name: ${APP_NAME}_nginx
    working_dir: /var/www/html
    hostname: ${APP_HOST}
    build:
      context: ./containers/nginx
      args:
        - APP_HOST=${APP_HOST}
    volumes:
      - ${APP_SRC}:/var/www/html
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - php-fpm
    networks:
      - project_network

  phpmyadmin:
    image: ${REPO_NAME}_phpmyadmin:${VERSION}
    container_name: ${APP_NAME}_phpmyadmin
    build:
      context: ./containers/phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD} 
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - project_network

  mailhog:
    image: ${REPO_NAME}_mailhog:${VERSION}
    container_name: ${APP_NAME}_mailhog
    build:
      context: ./containers/mailhog
    restart: on-failure
    expose:
      - "1025"
    ports:
      - 8025:8025
    networks:
      - project_network
  
  redis:
    image: ${REPO_NAME}_redis:${VERSION}
    container_name: ${APP_NAME}_redis
    build:
      context: ./containers/redis
    restart: on-failure
    expose:
      - 6379
    networks:
      - project_network
  
  chrome:
    image: ${REPO_NAME}_chrome:${VERSION}
    container_name: ${APP_NAME}_chrome
    build:
      context: ./containers/chrome
    networks:
      - project_network
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ""
      CHROMEDRIVER_PORT: "9515"
    ports:
      - 9515:9515
    cap_add:
      - "SYS_ADMIN"
    
  frontend:
    image: ${REPO_NAME}_frontend:${VERSION}
    container_name: ${APP_NAME}_frontend
    user: ${CURRENT_UID}
    command: 'php artisan serve --host=0.0.0.0'
    build:
      context: ./containers/frontend
    networks:
      - project_network
    ports:
      - 9999:8000
    volumes:
      - ${APP_SRC_FRONTEND}:/app